version: "3.3"
services:
  #  app:
  #    image: ok-marketplace-be-app-ktor:0.0.1
  #    ports:
  #      - "8080:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - "8180:8080"
      - "8182:9990"
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_ADMIN: nifont
      KEYCLOAK_ADMIN_PASSWORD: power

    command: start-dev
